{% set name = "QScreenCast" %}
{% set version = "0.1.41" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/QScreenCast-{{ version }}.tar.gz
  sha256: a00847072b1a77a903d13d1572100fa3ac91d5665bac87d93df363a7b038cd6d
  patches:
    # It seems that pyqt doesn't provide the right info for pip check to pass
    # Second, they forgot to ship the requirements/conda_run.txt in the
    # source distribution, so we can't patch out just the line
    # #Just remove the file all together
    - remove_pip_requirements.patch
    # If the file ever gets added back, we can use the following command
    # before the pip install command to remove the line that starts with pyqt
    # - sed '/^pyqt/d' requirements/conda_run.txt

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pyqt >=5.15.4
    - qtpy >=2.0.1
    - qtawesome >=1.1.1
  run:
    - ffmpeg
    - pyqt >=5.15.4
    - python >={{ python_min }}
    - qtawesome >=1.1.1
    - qtpy >=2.0.1

test:
  imports:
    - QScreenCast
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Semi-ATE/QScreenCast
  summary: A no-nonsense screen-caster behind a QToolButton.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
